name: Code Coverage

on: ['push', 'pull_request']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  registry-url: https://registry.npmjs.org/
            - run: npm install
            - run: npm run test
            - uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
