name: Publish

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
            #       registry-url: https://registry.npmjs.org/
            #   env:
            #       NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
            - run: npm install
            - run: npm test
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
            - uses: coverallsapp/github-action@master
